import Header from "@/components/header/Header";
import "./globals.css";

export const metadata = {
  title: "Home | DedxCRUD",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="max-w-3xl mx-auto p-4">
          <Header />
          <div className="mt-5">{children}</div>
          {/* footer  */}
        </div>
      </body>
    </html>
  );
}
