import AddTopic from "@/components/AddTopic/AddTopic";

export const metadata = {
  title: "Create Note | DedxNotes",
  description: "Generated by create next app",
};

const AddTopicPage = () => {
  return (
    <div className="min-h-screen">
      <AddTopic />
    </div>
  );
};

export default AddTopicPage;
