import AddTopic from "@/components/AddTopic/AddTopic";

export const metadata = {
  title: "Create Note | DedxNotes",
  description: "Generated by create next app",
};

const AddTopicPage = () => {
  return (
    <>
      <AddTopic />
    </>
  );
};

export default AddTopicPage;
