import AddTopic from "@/components/add-topic/AddTopic";

export const metadata = {
  title: "Add Topic | DedxCRUD",
  description: "Generated by create next app",
};

const AddTopicPage = () => {
  return (
    <>
      <AddTopic />
    </>
  );
};

export default AddTopicPage;
