import AddTopic from "@/components/add-topic/AddTopicComp";

export const metadata = {
  title: "Add Topic | DedxNotes",
  description: "Generated by create next app",
};

const AddTopicPage = () => {
  return (
    <>
      <AddTopic />
    </>
  );
};

export default AddTopicPage;
